### ISSUE TITLE
Could you update the code, please

### ISSUE THREAD

**Issue by mcuntz** [LI-COR/eddypro-engine#3] opened 2020-11-05 10:38 UTC
Dear EddyPro developers,

would it be possible to update the code to its latest version? We have a problem with the spectral corrections in version 7.0.6 but not with version 6.2.0. I wanted to debug but the current repo is not compiling on macOS Catalina (10.15.7) with gfortran 10.2.0. It stops at:

> gfortran -Wall -pedantic -fall-intrinsics -fbounds-check -Wextra -Wcharacter-truncation -Wunderflow -Wno-compare-reals -std=f2008 -O3 -I ../obj/mac/ -c ../src/src_rp/eddypro-rp_main.f90 -o ../obj/mac/eddypro-rp_main.o
> ../src/src_rp/eddypro-rp_main.f90:1557:92:
> 
>  1557 |                 if (EddYProProj%out_fluxnet) call WriteOutFluxnetOnlyBiomet(suffixOutString)
>       |                                                                                            1
> Error: More actual than formal arguments in procedure call at (1)
> ../src/src_rp/eddypro-rp_main.f90:1608:92:

The error is actually correct because WriteOutFluxnetOnlyBiomet is defined as

> subroutine WriteOutFluxnetOnlyBiomet()

in src/src_rp/write_out_fluxnet_only_biomet.f90.

Kind regards
Matthias Cuntz

**Comment by geryatejina** [comment] 2020-11-26 08:15
Closed as duplicate of [#2](https://github.com/LI-COR/eddypro-engine/issues/2).

**Closed** 2020-11-26 08:15 UTC
